---
title: HW3
---

```{r , setup}
#| code-fold: true

# load packages
library(httr)
library(jsonlite)
library(tidyverse)
library(broom)
library(readr)
library(gt)
library(openintro)
library(ggplot2)
library(modelr)
library(lterdatasampler)
library(sf)
library(dplyr)
library(maptiles)
library(kableExtra)
library(janitor)
library(sunburstR)
library(htmltools)
library(d3r)
library(plotly)
```

# Sunburst chart

### Define US regions

```{r , us_regions_df}

# create a data frame with columns for states and regions
us_state_region <- data.frame(
  state = c(
    "Maine", "Massachusetts", "Rhode Island", "Connecticut", "New Hampshire", 
    "Vermont", "New York", "Pennsylvania", "New Jersey", "Delaware", "Maryland",
    "District of Columbia","West Virginia", "Virginia", "Kentucky", "Tennessee", 
    "North Carolina", "South Carolina", "Georgia", "Alabama", "Mississippi", "Arkansas", 
    "Louisiana", "Florida",
    "Ohio", "Indiana", "Michigan", "Illinois", "Missouri", "Wisconsin", 
    "Minnesota", "Iowa", "Kansas", "Nebraska", "South Dakota", "North Dakota",
    "Texas", "Oklahoma", "New Mexico", "Arizona",
    "Colorado", "Wyoming", "Montana", "Idaho", "Washington", "Oregon", 
    "Utah", "Nevada", "California", "Alaska", "Hawaii"
  ),
  region = c(
    rep("Northeast", 12),
    rep("Southeast", 12),
    rep("Midwest", 12),
    rep("Southwest", 5),
    rep("West", 10)
  )
)

# view the dataset
head(us_state_region)
```

### Aggregate data by state

```{r}
us_fast_ports_per_state_df <- us_fast_ports_per_state %>% 
  rename(state = sf)

total_ports_per_state_df <- us_fast_ports_per_state_df %>%
  group_by(state) %>%
  summarise(
    total_fast_ports_per_state_pop = sum(total_fast_ports_per_pop_by_status),
    total_fast_ports_per_state = sum(total_fast_ports_by_status),
    total_pop_per_state = unique(total_pop_per_state),
    total_ports_per_cap = sum(total_fast_ports_per_pop)) %>% 
  ungroup()

# add regions to EV ports dataset
charging_ports_per_region <- left_join(total_ports_per_state_df, us_state_region, by = join_by(state == state)) %>% 
  arrange(region, desc(total_fast_ports_per_state)) %>% 
  select(region, state, total_fast_ports_per_state)

# view dataframe
knitr::kable(charging_ports_per_region)
```

### Sunburst viz

```{r}

dat <- data.frame(
  level1 = rep(c(charging_ports_per_region$region)),
  level2 = paste0(rep(c(charging_ports_per_region$state))),
  size = c(charging_ports_per_region$total_fast_ports_per_state),
  stringsAsFactors = FALSE
)

tree <- d3_nest(dat, value_cols = "size")

sb1 <- sunburst(tree, width="100%", height=400)
sb2 <- sunburst(
  tree,
  legend = FALSE,
  width = "100%",
  height = 400
)

# do side-by-side for comparison
div(
  style="display: flex; align-items:center;",
  div(style="width:50%; border:1px solid #ccc;", sb1),
  div(style="width:50%; border:1px solid #ccc;", sb2)
)
```



```{r}
sb3 <- sund2b(tree, width="100%")

div(
  style="display: flex; align-items:center;",
  sb3
)

```


